### ISSUE TITLE
polybar doesn't detect sink on boot

### ISSUE THREAD

**Issue by patrick-motard** [patrick-motard/dotfiles#57]
The polybar module will flash an error about the sink not existing, intermitently. Reloading i3 removes the error and the module works correctly.

**Comment by amasover** [comment]
It seems likely that the pulseaudio sink is not yet initialized when [this line runs in pulseaudio-tail.sh](https://github.com/patrick-motard/dotfiles/blob/master/.local/bin/tools/pulseaudio-tail.sh#L3).

There's 2 things to potentially fix here:

1. Fix error/flashing. Something more graceful should happen if a sink doesn't exist (for example, if no audio device is actually installed).

2. Somehow compensate for delay in sink initialization (if I'm correct about that being the cause). Or maybe only print the volume when we receive an event trigger of the sink being ready to use.

**Comment by patrick-motard** [comment]
I was thinking of looping while the command returns exit code 1 and pipeing output to Dev null. Removes the constant flashing of the error message and compensates for the initial failure of variable duration. I think.

**Comment by patrick-motard** [comment]
Feel free to fix, or I will later

**Comment by patrick-motard** [comment]
@amasover resolved. see commit above.
