### ISSUE TITLE
Rename install script

### ISSUE THREAD

**Issue by amasover** [patrick-motard/dotfiles#85]
GNU coreutils already has a program called `install`:

https://www.gnu.org/software/coreutils/manual/html_node/install-invocation.html

I suggest picking a different name.

**Comment by patrick-motard** [comment]
Good idea. i never call install. I call the aliases (described in the README.md) `setup-edit` and `setup-install`. I'm planning on moving these aliases as subcommands of my [dot repo](https://github.com/patrick-motard/dot):

- `dot install`
- `dot install edit`
- `dot update`
- `dot update edit`

etc. I'll leave this issue open until it's finished.

**Comment by patrick-motard** [comment]
Install should no longer be used. Documentation of it has been removed from the README. Installation and updating of dotfiles has been moved to [dot-ansible](https://github.com/patrick-motard/dot-ansible).

Updates are now done by running `update` in the terminal, which calls `dot-ansible`.

**Comment by patrick-motard** [comment]
Installation instructions have been updated in the README and the wiki for using dot-ansible.
