### ISSUE TITLE
pacman: mirror list out of date

### ISSUE THREAD

**Issue by patrick-motard** [patrick-motard/dotfiles#92]
Sometimes mirrors go out of date and no longer work when running `update`. The error looks like `failed to connect to archlinux mirror {OLD_MIRROR}:80 no route to host`. To fix this I searched for {OLD_MIRROR} in `/etc/pacman.d/mirrorlist` and found it at the top of the list. I switched it with the second mirror in the list.

After some brief searching on the issue it looks like it's possible to retrieve an updated list of mirrors and then sort them by speed using an arch package called `reflector`. It's not clear to me if reflector can get the new mirrorlist as well. Examples don't indicate to me that it can. Reflector can also be set up to run as a hook in pacman. Examples are on the arch wiki.

I'd like my OS to update it's mirrorlist and sort it by speed automatically before updating so that this doesn't require manual intervention again.

**Comment by patrick-motard** [comment]
relevant links: 
- https://www.garron.me/en/go2linux/how-to-find-the-fastest-archlinux-mirrors.html
- https://www.archlinux.org/packages/core/any/pacman-mirrorlist/
- https://wiki.archlinux.org/index.php/Reflector

**Comment by amasover** [comment]
I have a command to do this. I can share it with you when I get back from my trip tomorrow.

(I have a few other tweaks as well that I'm overdue on opening PRs for.)

**Comment by amasover** [comment]
Sorry for the delay. This is the command that I prefer:

```
sudo reflector --verbose --protocol https --age 8 --sort rate --save /etc/pacman.d/mirrorlist
```
